[build]
  publish = "."

[[redirects]]
  from = "/api/sheets/*"
  to = "https://docs.google.com/spreadsheets/d/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/github/*"
  to = "https://api.github.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"